--- #YAML:1.0
name:               Test-Pockito
version:            0.02
abstract:           ~
author:
    - Spencer Portee (exussum@gmail.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::MOP:           1.02
    IO::String:           1.08
    Scalar::Util::Reftype:  0.4
    Test::Simple:         0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
